//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaInfoDotNet.WFClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point WinPosition {
            get {
                return ((global::System.Drawing.Point)(this["WinPosition"]));
            }
            set {
                this["WinPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("624, 362")]
        public global::System.Drawing.Size WinSize {
            get {
                return ((global::System.Drawing.Size)(this["WinSize"]));
            }
            set {
                this["WinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\DS1010-CSC\\video\\")]
        public string LastLocation {
            get {
                return ((string)(this["LastLocation"]));
            }
            set {
                this["LastLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Videos\\Sample Videos\\Wildlife.wmv")]
        public string LastFile {
            get {
                return ((string)(this["LastFile"]));
            }
            set {
                this["LastFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveOnExit {
            get {
                return ((bool)(this["SaveOnExit"]));
            }
            set {
                this["SaveOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 20")]
        public global::System.Drawing.Point WinPositionHisto {
            get {
                return ((global::System.Drawing.Point)(this["WinPositionHisto"]));
            }
            set {
                this["WinPositionHisto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 360")]
        public global::System.Drawing.Size WinSizeHisto {
            get {
                return ((global::System.Drawing.Size)(this["WinSizeHisto"]));
            }
            set {
                this["WinSizeHisto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompleteInform {
            get {
                return ((bool)(this["CompleteInform"]));
            }
            set {
                this["CompleteInform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size WinSizePrefs {
            get {
                return ((global::System.Drawing.Size)(this["WinSizePrefs"]));
            }
            set {
                this["WinSizePrefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point WinPosPrefs {
            get {
                return ((global::System.Drawing.Point)(this["WinPosPrefs"]));
            }
            set {
                this["WinPosPrefs"] = value;
            }
        }
    }
}
